<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#audiobooks', 'url' => '/audiobooks', 'verb' => 'GET'],
		['name' => 'page#music', 'url' => '/music', 'verb' => 'GET'],
		['name' => 'page#playlists', 'url' => '/playlists', 'verb' => 'GET'],
		['name' => 'page#favoritesPlaylist', 'url' => '/playlists/favorites', 'verb' => 'GET'],
		['name' => 'page#playlist', 'url' => '/playlists/{id}', 'verb' => 'GET'],
		['name' => 'page#browse', 'url' => '/browse', 'verb' => 'GET'],
		['name' => 'page#nowPlaying', 'url' => '/now-playing', 'verb' => 'GET'],
		['name' => 'page#library', 'url' => '/library', 'verb' => 'GET'],
		['name' => 'page#settings', 'url' => '/settings', 'verb' => 'GET'],
		['name' => 'page#appSettings', 'url' => '/app-settings', 'verb' => 'GET'],

		['name' => 'api#listTracks', 'url' => '/api/tracks', 'verb' => 'GET'],
		['name' => 'api#getTrackInfo', 'url' => '/api/tracks/{fileId}', 'verb' => 'GET'],
		['name' => 'api#getPlayableTrack', 'url' => '/api/playable/{fileId}', 'verb' => 'GET'],
		['name' => 'api#listFolderTracks', 'url' => '/api/folders/{folderId}/tracks', 'verb' => 'GET'],
		['name' => 'api#getFolderListenedStats', 'url' => '/api/folders/listened-stats', 'verb' => 'GET'],
		['name' => 'api#setFolderPathListened', 'url' => '/api/folders/listened', 'verb' => 'PUT'],
		['name' => 'api#setFolderListened', 'url' => '/api/folders/{folderId}/listened', 'verb' => 'PUT'],
		['name' => 'api#listCollections', 'url' => '/api/collections', 'verb' => 'GET'],
		['name' => 'api#getCollection', 'url' => '/api/collections/{key}', 'verb' => 'GET'],
		['name' => 'api#listFacets', 'url' => '/api/facets/{type}', 'verb' => 'GET'],
		['name' => 'api#getProgress', 'url' => '/api/progress', 'verb' => 'GET'],
		['name' => 'api#saveProgress', 'url' => '/api/progress/{fileId}', 'verb' => 'PUT'],
		['name' => 'api#saveProgressBeacon', 'url' => '/api/progress/{fileId}', 'verb' => 'POST'],
		['name' => 'api#deleteProgress', 'url' => '/api/progress/{fileId}', 'verb' => 'DELETE'],
		['name' => 'api#getQueue', 'url' => '/api/queue', 'verb' => 'GET'],
		['name' => 'api#saveQueue', 'url' => '/api/queue', 'verb' => 'PUT'],
		['name' => 'api#saveQueueBeacon', 'url' => '/api/queue', 'verb' => 'POST'],
		['name' => 'api#clearQueue', 'url' => '/api/queue', 'verb' => 'DELETE'],
		['name' => 'api#listPlaylists', 'url' => '/api/playlists', 'verb' => 'GET'],
		['name' => 'api#createPlaylist', 'url' => '/api/playlists', 'verb' => 'POST'],
		['name' => 'api#buildPlaylist', 'url' => '/api/playlists/build', 'verb' => 'POST'],
		['name' => 'api#getPlaylist', 'url' => '/api/playlists/{id}', 'verb' => 'GET'],
		['name' => 'api#updatePlaylist', 'url' => '/api/playlists/{id}', 'verb' => 'PUT'],
		['name' => 'api#deletePlaylist', 'url' => '/api/playlists/{id}', 'verb' => 'DELETE'],
		['name' => 'api#addPlaylistItem', 'url' => '/api/playlists/{id}/items', 'verb' => 'POST'],
		['name' => 'api#reorderPlaylistItems', 'url' => '/api/playlists/{id}/items/reorder', 'verb' => 'PUT'],
		['name' => 'api#removePlaylistItem', 'url' => '/api/playlist-items/{id}', 'verb' => 'DELETE'],
		['name' => 'api#listLibraries', 'url' => '/api/libraries', 'verb' => 'GET'],
		['name' => 'api#addLibrary', 'url' => '/api/libraries', 'verb' => 'POST'],
		['name' => 'api#updateLibrary', 'url' => '/api/libraries/{id}', 'verb' => 'PUT'],
		['name' => 'api#removeLibrary', 'url' => '/api/libraries/{id}', 'verb' => 'DELETE'],
		['name' => 'api#scanStatus', 'url' => '/api/scan', 'verb' => 'GET'],
		['name' => 'api#scanAjaxCronTick', 'url' => '/api/scan/ajax-cron', 'verb' => 'GET'],
		['name' => 'api#triggerScan', 'url' => '/api/scan', 'verb' => 'POST'],
		['name' => 'api#getPrefs', 'url' => '/api/prefs', 'verb' => 'GET'],
		['name' => 'api#savePrefs', 'url' => '/api/prefs', 'verb' => 'PUT'],
		['name' => 'api#searchUsers', 'url' => '/api/admin/users', 'verb' => 'GET'],
		['name' => 'api#searchGroups', 'url' => '/api/admin/groups', 'verb' => 'GET'],
		['name' => 'api#setFavorite', 'url' => '/api/tracks/{fileId}/favorite', 'verb' => 'PUT'],
		['name' => 'api#setListened', 'url' => '/api/tracks/{fileId}/listened', 'verb' => 'PUT'],
		['name' => 'api#setListenedBulk', 'url' => '/api/listened/bulk', 'verb' => 'PUT'],
		['name' => 'api#queryListenedMap', 'url' => '/api/listened/query', 'verb' => 'POST'],
		['name' => 'api#getLibrarySyncState', 'url' => '/api/library/sync-state', 'verb' => 'GET'],
		['name' => 'api#setCollectionListened', 'url' => '/api/collections/{key}/listened', 'verb' => 'PUT'],
		['name' => 'api#getAppPolicy', 'url' => '/api/admin/policy', 'verb' => 'GET'],
		['name' => 'api#saveAppPolicy', 'url' => '/api/admin/policy', 'verb' => 'POST'],

		['name' => 'stream#play', 'url' => '/api/stream/{fileId}', 'verb' => 'GET'],
		['name' => 'cover#get', 'url' => '/api/cover/{fileId}', 'verb' => 'GET'],
	],
];
